######################################################################
# Automatically generated by qmake (2.01a) sam. juin 15 22:36:25 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fenetre.h main.h
SOURCES += fenetre.cpp main.cpp
