######################################################################
# Automatically generated by qmake (2.01a) ven. juin 14 17:59:40 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
