######################################################################
# Automatically generated by qmake (2.01a) dim. juin 16 22:24:22 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fenetre.h main.h
SOURCES += fenetre.cpp main.cpp
